apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: terrastack
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: terrastack-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000       # your FastAPI app uses 8000 in Dockerfile
          env:
            - name: DB_HOST
              value: db-svc           # must match your DB service name
            - name: DB_NAME
              value: terrastack
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password