apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: terrastack
spec:
  replicas: {{ .Values.replicaCount.backend }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.image.backend.repository }}:{{ .Values.image.backend.tag }}
          ports:
            - containerPort: {{ .Values.service.backend.port }}
          envFrom:
            - configMapRef:
                name: terrastack-config