apiVersion: v1
kind: ConfigMap
metadata:
  name: terrastack-config
  namespace: terrastack
data:
  BACKEND_URL: "http://api-svc:8081"
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_NAME: {{ .Values.db.name }}