apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: terrastack
spec:
  replicas: {{ .Values.replicaCount.db }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{ .Values.image.db.repository }}:{{ .Values.image.db.tag }}
          ports:
            - containerPort: {{ .Values.service.db.port }}
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: password
            - name: POSTGRES_DB
              value: terrastack
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: db-pvc