apiVersion: apps/v1
kind: Deployment
metadata:
  name: terrastack-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terrastack-db
  template:
    metadata:
      labels:
        app: terrastack-db
    spec:
      containers:
      - name: postgres
        image: {{ .Values.db.image }}
        env:
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.password }}
        - name: POSTGRES_DB
          value: terrastack
        ports:
        - containerPort: 5432