apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: terrastack
spec:
  selector:
    app: frontend
  ports:
    - port: {{ .Values.service.frontend.port }}
      targetPort: {{ .Values.service.frontend.port }}
  type: LoadBalancer