apiVersion: v1
kind: PersistentVolume
metadata:
  name: terrastack-data-pv
  namespace: terrastack
spec:
  capacity:
    storage: {{ .Values.db.dataStorage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/terrastack