apiVersion: v1
kind: PersistentVolume
metadata:
  name: terrastack
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /d/timot/workspaces/interviews/TerraStack/data
  persistentVolumeReclaimPolicy: Retain