apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terrastack-data-pvc
  namespace: terrastack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.dataStorage }}