replicaCount: 1

image:
  frontend: frontend:latest
  backend: backend:latest
  db: mysql:5.7

service:
  type: ClusterIP
  frontendPort: 80
  backendPort: 3000
  dbPort: 3306

resources: {}