apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: terrastack
type: Opaque
stringData:
  username: {{ .Values.secret.dbUser }}
  password: {{ .Values.secret.dbPassword }}