replicaCount:
  frontend: 2
  backend: 1
  db: 1

image:
  frontend:
    repository: terrastack-frontend
    tag: latest
    pullPolicy: IfNotPresent
  backend:
    repository: terrastack-backend
    tag: latest
    pullPolicy: IfNotPresent
  db:
    repository: terrastack-db
    tag: latest
    pullPolicy: IfNotPresent

service:
  frontend:
    type: LoadBalancer
    port: 80
  backend:
    type: ClusterIP
    port: 8081
  db:
    type: ClusterIP
    port: 5432

db:
  name: terrastack
  user: terrastack
  password: terrastack
  dataStorage: 1Gi